apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitoring-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: monitoring
  template:
    metadata:
      labels:
        app: monitoring
    spec:
      containers:
        - name: monitoring-container
          image: <your_aws_account_id>.dkr.ecr.<region>.amazonaws.com/monitoring-app:latest
          ports:
            - containerPort: 5000